title = "tsukumaru's Website"
baseURL = "https://tsukumaru.github.io/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
publishDir = "docs"

[params]
address = ""
email = ""
favicon = "/favicon.ico"
firstName = "tsukumaru / shiomusubi"
lastName = ""
phone = ""
profileImage = "img/tsukumaru.jpeg"
showEducation = false
showExperience = false
showOpenSource = false
showProjects = true
showPublications = true
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://twitter.com/maruju_fav"
name = "Twitter"
icon = "twitter"

[[params.handles]]
link = "https://tsukumaru.hateblo.jp/"
name = "Blog"
icon = "blog"
prefix = "fas"

[[params.handles]]
link = "https://qiita.com/tsukumaru"
name = "Qiita"
icon = "blog"
prefix = "fas"

[[params.handles]]
link = "https://github.com/tsukumaru/"
name = "GitHub"

[[params.handles]]
link = "https://speakerdeck.com/tsukumaru"
name = "Speaker Deck"
icon = "speaker-deck"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"